# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.path.upload: '%env(UPLOAD_DIR)%'
    api.base_url: '%env(resolve:API_BASE_URL)%'
    api.context_path: 'contexts'
    http_kernel.cors.allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
    http_kernel.cors.allow_methods: [ 'GET', 'OPTIONS' ] # 'POST', 'PUT', 'PATCH', 'DELETE'
    http_kernel.cors.allow_headers: [ 'Content-Type', 'Authorization', 'Origin', 'X-Requested-With', 'Accept' ]
    http_kernel.cors.allow_path: '%env(resolve:API_BASE_URL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
